### ISSUE TITLE
[Parachain Onboarding | Slot Request] ParaId: 2058

### ISSUE THREAD

**Issue by Mrigesh901** [paseo-network/support#108] opened 2024-10-23 05:50 UTC
### Parachain Name

Watr Network

### ParaID

2058

### Parachain Manager Account

13zZ9kTHjuJ7gYox4ddWGXNNT2zLNCZYmJbhr1yT2RezLUmM

### Upload your Genesis State - Do not submit a compressed file.

[parachain-genesis-head-for-paseo.txt](https://github.com/user-attachments/files/17485769/parachain-genesis-head-for-paseo.txt)

### Upload your Validation Code (genesis runtime Wasm) - Do not submit a compressed file.

[parachain-genesis-wasm-for-paseo.txt](https://github.com/user-attachments/files/17485774/parachain-genesis-wasm-for-paseo.txt)

**Comment by Mrigesh901** [comment] 2024-10-24 07:38
Hi @hbulgarini @al3mart , just checking in on the onboarding issue - any chance we could get an update or speed up the process? Thanks for your help!

**Comment by rahul-mnz** [comment] 2024-10-25 12:08
Hi @hbulgarini @al3mart , we have funded the wallet with some paseo as required. Please proceed with the onboarding. Thanks

**Comment by al3mart** [comment] 2024-10-25 12:42
![image](https://github.com/user-attachments/assets/ee7dcd10-19cd-4487-b306-5743485badb1)

The chain is now being registered.

**Comment by rahul-mnz** [comment] 2024-10-25 15:56
So lease ( coretime ) will also be assigned to the chain, since its not producing any block and no option to purchase coretime as of now ? Please do help out with this as we need to make the chain live as soon as possible.

**Comment by Mrigesh901** [comment] 2024-10-28 07:54
@al3mart , is the slot assigned to this parachain? No blocks are currently being produced.

**Comment by al3mart** [comment] 2024-10-29 08:42
Right, you are free to procure yourselves some coretime via on demand or bulk coretime sales :+1: 
- Please find more info at: https://wiki.polkadot.network/docs/learn-guides-coretime-parachains

You might need some bigger balance than what the facuet might drip, so please, feel free to ask for a top up

**Comment by al3mart** [comment] 2024-10-29 08:49
I have manually assigned your parachain to a core. Please, let us know if you face any other issues

**Comment by al3mart** [comment] 2024-10-29 08:51
> no option to purchase coretime as of now ?

Regarding this, I have just checked and there are 5 cores open to be purchased :thinking: 

An easier way to interact with the sales might be using an app like https://app.regionx.tech/?network=paseo

**Comment by Mrigesh901** [comment] 2024-10-30 04:43
@al3mart , we are getting error and parachain not producing blocks.
[Parachain] Could not find the header of the genesis block in the database! block_hash=0xa797f540918262535748f8d2c284ad39c2f73f426570656ca3985d36807eb6f1

I rechecked, the genesis-head and wasm shared here on github issue is same as on node.
I wiped the parachain data on all collator nodes and restarted all nodes, but it did not work either.

**Comment by al3mart** [comment] 2024-10-30 09:24
Xposting here from  the public support channel:

We have registered the wasm and the state you have shared with us.
The chain is assigned in a core.

The problem is either you have shared with us the wrong genesis state and wasm, or you are running on some old db.
Please, make sure that you have prunned the parachain DB, and that you are using the correct spec for paseo and your parachain. Maybe even prune paseo's DB and sync again

> `[Parachain] Could not find the header of the genesis block in the database! block_hash=0xa797f540918262535748f8d2c284ad39c2f73f426570656ca3985d36807eb6f1`

So, there's a clear mismatch on the expected genesis state, and that is something we are not generating

**Comment by al3mart** [comment] 2024-10-31 09:11
Bringing some context from our conversations in the public support channel:

The uploaded state file registered in the relay contains the following head:

`0x000000000000000000000000000000000000000000000000000000000000000000d10de30370438ba64bba182ed96f92ac12c3f8c5dd0636db91c39846cfba3b2c03170a2e7597b7b7e3d84c05391d139a62b157e78786d8c082f29dcf4c11131400` 

The nodes show the following header-hash at lunch:

`Initializing Genesis block/state (state: 0x7304…5d7a, header-hash: 0x3356…88c1)`

**Comment by al3mart** [comment] 2024-11-01 07:43
If you could share the spec you are using here we could double check the information in the relay in a more agile way.

**Comment by Mrigesh901** [comment] 2024-11-01 08:45
https://drive.google.com/file/d/1JZkeuvYZRNOKTfCc-kh2dRSR0w4sIOg9/view?usp=sharing

This is the chainspec using which we created genesis-head and wasm

**Comment by Mrigesh901** [comment] 2024-11-01 08:50
Now we have removed the childrenDefault entries from chainspec, and now new genesis head and wasm is created, it is matching the state the chain is looking for when node is started with new chainspec.
Genesis head :
[genesis-head.txt](https://github.com/user-attachments/files/17597887/genesis-head.txt)


Genesis-wasm:
[genesis-wasm.txt](https://github.com/user-attachments/files/17597891/genesis-wasm.txt)

**Comment by Mrigesh901** [comment] 2024-11-01 08:51
https://drive.google.com/file/d/1SxWZHihu4AkKLczgvkKCTcufZOZPfwI6/view?usp=sharing
New chainspec

**Comment by hbulgarini** [comment] 2024-11-01 10:38
> Now we have removed the childrenDefault entries from chainspec, and now new genesis head and wasm is created, it is matching the state the chain is looking for when node is started with new chainspec. Genesis head : [genesis-head.txt](https://github.com/user-attachments/files/17597887/genesis-head.txt)
> 
> Genesis-wasm: [genesis-wasm.txt](https://github.com/user-attachments/files/17597891/genesis-wasm.txt)

Both values were updated in the relay.

**Comment by Mrigesh901** [comment] 2024-11-01 10:46
![image](https://github.com/user-attachments/assets/855b8fd1-a586-4502-9930-54168da07a34)

**Comment by Mrigesh901** [comment] 2024-11-01 11:58
https://github.com/Watr-Protocol/watr/blob/main/chain-specs/devnet-raw.json

This is the chainspec before migration, the one we were using for rococo.

**Comment by hbulgarini** [comment] 2024-11-01 12:24
> ![image](https://private-user-images.githubusercontent.com/59439845/382259373-855b8fd1-a586-4502-9930-54168da07a34.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0NTk3MDYsIm5iZiI6MTczMDQ1OTQwNiwicGF0aCI6Ii81OTQzOTg0NS8zODIyNTkzNzMtODU1YjhmZDEtYTU4Ni00NTAyLTk5MzAtNTQxNjhkYTA3YTM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAxVDExMTAwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3MGYzZWVhMjZhODY1YjRjNmNlZTA5ZjZlODUyYmM1ZmI5Y2YzMzA3YzgyZDgxNjRhNjQ0OTQ5MTU1YTEwMTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5CFRwBB0D7ciixGD5Of5Ya98Wg-xEstvVgGZq8fuVCw)

this is something we can fix from our side as we can push the value for dmp queue. I have updated the relay storage item with the right expected value:

0x56ec24b73e27c4526c8b7584b94d62f416a9052359e4a9bfb62477746df677aa

could you please check now?

**Comment by Mrigesh901** [comment] 2024-11-01 12:57
@al3mart @hbulgarini , the chain is up. Thanks for all the help.

**Comment by hbulgarini** [comment] 2024-11-01 13:09
> @al3mart @hbulgarini , the chain is up. Thanks for all the help.

congratulations! i'm glad we finally did it!

closing the issue for now.

**Closed as completed by hbulgarini** 2024-11-01 13:09 UTC
Labels: onboard-para
